# Generated by Django 5.1.6 on 2025-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donation_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='ammu@gmail.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='ammu@gmail.com', max_length=40),
            preserve_default=False,
        ),
    ]
