# Generated by Django 5.1.6 on 2025-05-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donor_email_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_request',
            name='amount_raised',
        ),
        migrations.AddField(
            model_name='donation_request',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_docs/'),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/income_certs/'),
        ),
    ]
