# Generated by Django 5.1.6 on 2025-05-20 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_remove_donation_request_amount_raised_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_request',
            name='title',
        ),
        migrations.AddField(
            model_name='donation_request',
            name='catogery',
            field=models.CharField(choices=[('Books', 'Books'), ('Tution', 'Tution'), ('Uniform', 'Uniform'), ('Laptop', 'Laptop'), ('Others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
