# Generated by Django 5.1.6 on 2025-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_remove_donation_request_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='catogery',
            field=models.CharField(choices=[('Books', 'Books'), ('Tution', 'Tution'), ('Uniform', 'Uniform'), ('Laptop', 'Laptop'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
